### ISSUE TITLE
Scoped API without storeId emulates incorrect store

### ISSUE THREAD

**Issue by rain2o** [SnowdogApps/magento2-cms-api#14]
When calling `getList` for either Blocks or Pages it tries to find `storeId` in the URL params and emulates the resulting store ID. If no store ID is found (or more than 1) it uses `0` as the default store ID. 

The problem this introduces is if you are using the `store_code` scope in your API calls (following [Magento's recommended](https://devdocs.magento.com/guides/v2.3/rest/tutorials/index.html) pattern `<HTTP verb> http://<host>/rest/<scope>/<endpoint>` where `<scope>` can be `all`, `default`, or the store code) you will not necessarily pass the storeId because you don't need to. Magento's WebApi PathProcessor will set the current store based on the store code found using `StoreManagerInterface`. The code in `BlockManager` and `PageManager` overrides that by emulating store ID of `0` if no store ID found. 

This issue was discovered while testing the retrieval of CMS data from [Vue Storefront](https://github.com/DivanteLtd/vue-storefront). Specifically I received an error when it tries to render the `ProductsList` widget because it is attempting to create a product collection using the store ID 0 when it should be for the store code passed in the scoped API call.

The easiest solution is probably to do a check before calling the emulator to see if the result of `$storeId = $this->getStoreIdBySearchCriteria($searchCriteria);` is 0, and if so skip the emulation call. Not sure if this introduces other issues but it's the first idea I had.

**Comment by jochhop** [comment]
Hi @rain2o thanks for opening the issue, we'll check it and give some information soon

**Comment by jochhop** [comment]
Hi @rain2o , I am sorry for the delay, finally we could check this issue, we have added similar changes to the ones that you suggested:

> The easiest solution is probably to do a check before calling the emulator to see if the result of $storeId = $this->getStoreIdBySearchCriteria($searchCriteria); is 0, and if so skip the emulation call. Not sure if this introduces other issues but it's the first idea I had.

The new changes are now in release 1.7.0

thank you for the contribution and have a great day

**Comment by timdk** [comment]
Hi @jochhop, I found this issue because I think that it still affects the `/search` endpoint.

I have a second store view set up with code `de` for German.
I am receiving different content when I query all pages via the `/search` endpoint and when I query a page by its ID.

When I search for pages with `/rest/de/V1/snowdog/cmsPage/search?searchCriteria=undefined` the page content is all from the default view in English.

If I query a specific page like `/rest/de/V1/snowdog/cmsPage/5`, the content is in German as expected.

If I specify the store ID in the searchCriteria `/rest/de/V1/snowdog/cmsPage/search?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][value]=de` I get the correct German content, although the pages still have `"store_id": [ 0 ]` on the response.

Can you tell me, is this the expected behaviour for the search endpoint?
